### ISSUE TITLE
Add iptable based loadbalancing

### ISSUE THREAD

**Issue by scthi** [boehr/avatar#6]
- the "external" access point of the service should not change (http://getcatchapp.com:8888)
- an instance can be launch on a specific port with `bin/avatar <port-number>`
- every instance should be "controlled"
- it should be easy to 
  - add/remove an instance
  - stop all instances
  - restart all instances
- best would be if the scripts for the previous point are located in the `bin` folder of this repo 
- you may also add some documentation to the README.MD of this repo

**Comment by Dimmy15** [comment]
LoadBalancing for Avatar Service is active. There is a Startscript at:

```
/opt/hojoki/deploy/trunk/script/webserver/startAvatar.sh
```

It takes the Parameters start [num] , stop and status [num].
- start [num]: Starts "num" instances of avatar and installs iptables Rules to balance RR between them. Default "num" is 6
- stop: Stops all Avatar Processes and deletes RR iptable Rules
- status [num]: Checks if the number of Avatarsevices and iptables Rules matches "num". On success it will do nothing; on failure it will restart all Avatarservices. Default "num" is 6
